apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    name: counter
spec:
  containers:
    - name: app
      image: ghcr.io/subicura/counter:latest
      env:
        - name: REDIS_HOST
          value: "localhost"
    - name: db
      image: redis
