apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    name: mariadb
spec:
  containers:
    - name: mariadb
      image: mariadb:10.7
      env:
        - name: MYSQL_DATABASE
          value: "wordpress"
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
