apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-redis
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
      tier: redis
  template:
    metadata:
      labels:
        app: vote
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: vote-redis
  labels:
    app: vote
spec:
  selector:
    app: vote
    tier: redis
  ports:
    - port: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-db
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
      tier: db
  template:
    metadata:
      labels:
        app: vote
        tier: db
    spec:
      containers:
        - name: db
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: vote-db
  labels:
    app: vote
spec:
  selector:
    app: vote
    tier: db
  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
      tier: worker
  template:
    metadata:
      labels:
        app: vote
        tier: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/subicura/voting/worker:latest
          env:
            - name: REDIS_HOST
              value: "vote-redis"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: "vote-db"
            - name: POSTGRES_PORT
              value: "5432"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
      tier: vote
  template:
    metadata:
      labels:
        app: vote
        tier: vote
    spec:
      containers:
        - name: vote
          image: ghcr.io/subicura/voting/vote:latest
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "vote-redis"
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  selector:
    app: vote
    tier: vote
  ports:
    - port: 80
      nodePort: 31000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-result
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
      tier: result
  template:
    metadata:
      labels:
        app: vote
        tier: result
    spec:
      containers:
        - name: result
          image: ghcr.io/subicura/voting/result:latest
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: "vote-db"
            - name: POSTGRES_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: vote-result
  labels:
    app: vote
spec:
  type: NodePort
  selector:
    app: vote
    tier: result
  ports:
    - port: 80
      nodePort: 31001
